version: '3'
services:
  redis:
    image: redis
    ports:
      - '6378:6379'
    networks:
      - webnet
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123Rombik321
      POSTGRES_DB: chat
    ports:
      - '5433:5432'
    networks:
      - webnet
  node:
    image: node
    ports:
      - '3000:3000'
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6378
      POSTGRES_HOST: db
      POSTGRES_PORT: 5433
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123Rombik321
      POSTGRES_DB: chat
      SECRET_KEY: secret_key_somesecret
    depends_on:
      - db
      - redis
    networks:
      - webnet
networks:
  webnet:
    driver: bridge
